version: '2'
services:
    redis:
        image: redis:3.0-alpine
        container_name: "redis"

    server:
        build:
          context: ..
          dockerfile: docker/Dockerfile.server
        ports:
          - 9000:9000

