version: '2'
services:
    redis:
        image: redis:3.0-alpine
        container_name: "redis"

    server:
        build:
            context: ..
            dockerfile: Dockerfile.server
        ports:
            - 9000:9000

    callee:
        build:
            context: ..
            dockerfile: Dockerfile.callee

    client:
        build:
            context: ..
            dockerfile: Dockerfile.client

