version: '2'
services:
    # redis pubsub and redis caller
    redisp:
        image: redis:3.0-alpine
        container_name: "redisp"
    redisc:
        image: redis:3.0-alpine
        container_name: "redisc"
        command: ["redis-server", "--maxclients", "100000"]

    server:
        build:
            context: ..
            dockerfile: Dockerfile.server
        command: ["./juggler-server", "--config", "./docker/server.config.2.yml"]
        entrypoint: ./docker/docker_start.2.sh
        ports:
            - 9000:9000

    callee:
        build:
            context: ..
            dockerfile: Dockerfile.callee
        command: ["./juggler-callee", "--redis", "redisc:6379", "--workers", "100", "-n", "100", "--redis-max-idle", "1000"]
        entrypoint: ./docker/docker_start.2.sh

    client:
        build:
            context: ..
            dockerfile: Dockerfile.client

